MODEL:
  NAME: 'Fang'
  BACKBONE:
    NAME: 'CNN'
    INPUT_RESOLUTION: 28
    INPUT_CHENNEL: 1
    OUT_CHENNELS: 50
  CNN:
    CONV: [[30, 1], [50, 1]]
    KERNEL_SIZE: 3
    POOLER_SCALE: [0.5, 0.25]
    POOLER_SIZE: 2
  CLASSIFIER:
    HIDDEN_LAYERS: [200, ]
    NUM_CLASSES: 10

DATASETS:
  TRAIN: ('data', )
  VAL: ('data', )
  TRAIN_BATCH_SIZE: 10

SOLVER:
  CUDA: True
  STRATEGY: 'MBGD'
  LEARNING_RATE: 0.1
  MOMENTUM: 0.9
  MAX_EPOCH: 100

  GAMMA: 0.1
  CHECKPOINT: 100
  OUTPUT_DIR: 'checkpoint/'
