MODEL:
  NAME: 'ResNet-50'
  BACKBONE:
    NAME: 'ResNet-50'
    INPUT_RESOLUTION: 32
    INPUT_CHENNEL: 3
    OUT_CHENNELS: 2048
  RESNET:
    BLOCK_NUM: [0, 3, 4, 6, 3]
    POOLER_SCALE: [0.5, 0.25, 0.125, 0.0625, 0.03125]
  CLASSIFIER:
    NUM_CLASSES: 10

DATASETS:
  TRAIN: ('data', )
  VAL: ('data', )
  TRAIN_BATCH_SIZE: 64

SOLVER:
  CUDA: True
  STRATEGY: 'MBGD'
  LEARNING_RATE: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1.0e-4
  MAX_EPOCH: 500

  WARMUP_EPOCHS: 10
  WARMUP_FACTOR: 0.1
  WARMUP_METHOD: 'linear'
  WEIGHT_DECAY_BIAS: 0
  GAMMA: 0.1
  STEPS: [300, 400, ]
  CHECKPOINT: 100
  OUTPUT_DIR: 'checkpoint/'
