MODEL:
  NAME: 'SingleLayer'
  BACKBONE:
    NAME: 'CNN'
    INPUT_RESOLUTION: 28
  CLASSIFIER:
    NUM_CLASSES: 10

DATASETS:
  TRAIN: ('data', )
  VAL: ('data', )
  TRAIN_BATCH_SIZE: 10

SOLVER:
  CUDA: True
  STRATEGY: 'MBGD'
  LEARNING_RATE: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1.0e-4
  MAX_EPOCH: 100

  GAMMA: 0.1
  CHECKPOINT: 100
  OUTPUT_DIR: 'checkpoint/'
