MODEL:
  NAME: 'VGG11'
  BACKBONE:
    NAME: 'VGG11'
    INPUT_RESOLUTION: 32
    INPUT_CHENNEL: 1
    OUT_CHENNELS: 512
  CNN:
    CONV: [[64, 1], [128, 1], [256, 2], [512, 2], [512, 2]]
    KERNEL_SIZE: 3
    POOLER_SCALE: [0.5, 0.25, 0.125, 0.0625, 0.03125]
    POOLER_SIZE: 2
  CLASSIFIER:
    NUM_CLASSES: 10

DATASETS:
  TRAIN: ('data', )
  VAL: ('data', )
  TRAIN_BATCH_SIZE: 64

SOLVER:
  CUDA: True
  STRATEGY: 'MBGD'
  LEARNING_RATE: 0.1
  MOMENTUM: 0.9
  WEIGHT_DECAY: 1.0e-4
  MAX_EPOCH: 30

  WARMUP_EPOCHS: 3
  WARMUP_FACTOR: 0.1
  WARMUP_METHOD: 'linear'
  WEIGHT_DECAY_BIAS: 0
  GAMMA: 0.1
  STEPS: [300, 400 , ]
  CHECKPOINT: 100
  OUTPUT_DIR: 'checkpoint/'
